### ISSUE TITLE
Create a UML Class Diagram for our solution

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/group7_project4#1]
> This step should result in a UML Class Diagram that represents the class structure of all Java components in your Battleship game, including any additions or modifications required for the features in this stage. The diagram should show that your code structure adheres to the Single Responsibility Principle and that there is no code duplication. The diagram must match the version of your group's code that is submitted at the end of this assignment. This diagram can either be composed using UML modeling software, or drawn on paper (drawings should be labelled and legible). Scan and add this diagram to your group's Wiki pages.

- Code adheres to Single Responsibility Principle
- Match code submitted at end of assignment
- Add to wiki pages when finished

**Comment by ghost** [comment]
UML class Diagram is posted in the repo's wiki
