### ISSUE TITLE
Implement UI feature allowing the user to select the AI's difficulty (easy or hard)

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/group7_project4#2]
> The computer should have an Easy and Hard difficulty setting.

We need a way for the user to specify this with the user interface.

**Comment by CMCarlsen** [comment]
This issue has been addressed in PR #11 . Woo!

**Comment by CMCarlsen** [comment]
With the acceptance of PR #11 , I'm going to go ahead and close this issue. =)
